alpha: 0.4
batch_size_test: 64
batch_size_train: 8
bert_config: configs/config_bert-fullca.json
embed_dim: 256
eval_epoch: 0
image_res: 384
k_test: 128
mask_ratio: 0.75
max_words: 70
mlm_probability: 0.15
momentum: 0.995
mrtd_mask_probability: 0.3
optimizer: {lr: 1e-05, lr_custm: 0.0001, opt: adamW, weight_decay: 0.02}
queue_size: 65536
schedular: {cooldown_epochs: 0, decay_rate: 1, epochs: 30, lr: 1e-05, min_lr: 1e-06,
  sched: cosine, warmup_epochs: 1, warmup_lr: 1e-05}
temp: 0.07
test_file: ./datasets//RSTPReid/processed_data/test.json
test_image_root: ./datasets//RSTPReid/imgs
train_file: [./datasets//RSTPReid/processed_data/train.json]
train_image_root: ./datasets//RSTPReid/imgs
val_file: ./datasets//RSTPReid/processed_data/val.json
val_image_root: ./datasets//RSTPReid/imgs
vision_width: 768
warm_up: true
weak_pos_pair_probability: 0.1
weights: [0.5, 1, 1, 0.5, 0.5, 1, 2]